### ISSUE TITLE
Error: Setting onMessage on a WebView...

### ISSUE THREAD

**Issue by Enricopv** [donovantc/react-native-intercom-webview#6] opened 2018-02-10 01:37 UTC
[edit:] 

Using an anroid emulator, I see this in the console:
::ffff:192.168.1.87 - - [10/Feb/2018:02:20:34 +0000] "GET /favicon.ico HTTP/1.1" 404 24 "http://192.168.1.87:19001/assets/node_modules/react-native-intercom-webview/IntercomWebView.html?platform=android&hash=[our hash]" "Mozilla/5.0 (Linux; Android 8.0.0; PREVIEW - Google Pixel - 8.0 - API 26 - 1080x1920 Build/OPR6.170623.017; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.125 Mobile Safari/537.36"

Hope this helps!

[/edit]

Hello, we are having trouble using this plugin! I am using Expo. Using the plugin as outlined (except with our own appId) gives us this error:

![intercom](https://user-images.githubusercontent.com/7062889/36056918-6ff7ef30-0dbd-11e8-85ac-ecb9ddaa00fc.jpg)
I'm not sure what the problem is, but perhaps it's related to #5 ? 

I can get rid of the error applying the solution here: https://github.com/facebook/react-native/issues/10865 by kyle-ilantzis, but I'm just left with a blank view (below):

![intercomblank](https://user-images.githubusercontent.com/7062889/36057142-911a43aa-0dbf-11e8-9bba-8a1b0a9a7a45.jpg)

Below is my code
```
export default class Index extends Component {
  render() {      
    return (
      <Grid style={{backgroundColor: 'white'}}>
        <Row size={1}>
          <TopBar title={this.props.title} />
        </Row>
        <Row size={9} style={{backgroundColor: 'white'}}>          
          <IntercomWebView
            appId={"ourAppId"}
            name={"ourUsersName"}
            email={"ourUsersEmail"}
            defaultHeight={500}
            hideLauncher={false}
            showLoadingOverlay={true} 
            injectedJavaScript={patchPostMessageJsCode}
          />
        </Row>
        <Row>
          <Text>
            something
          </Text>
        </Row>
      </Grid>
    );
  }
}

const patchPostMessageFunction = function() {
  var originalPostMessage = window.postMessage;

  var patchedPostMessage = function(message, targetOrigin, transfer) { 
    originalPostMessage(message, targetOrigin, transfer);
  };

  patchedPostMessage.toString = function() { 
    return String(Object.hasOwnProperty).replace('hasOwnProperty', 'postMessage');
  };

  window.postMessage = patchedPostMessage;
};

const patchPostMessageJsCode = '(' + String(patchPostMessageFunction) + ')();';
```

Thanks in advance!

**Comment by donovantc** [comment] 2018-02-13 20:27
Hi @Enricopv. This should be fixed in the latest release v1.2.3, thanks to the [PR](https://github.com/donovantc/react-native-intercom-webview/pull/5) from @hironarita which I just merged.

So I'll close the issue for now. If the issue persists, feel free to open it again.

**Comment by Enricopv** [comment] 2018-02-13 22:49
Hey thanks for merging this change. We are able to get a step further in this but are still stuck. When loading the webview, I am stuck seeing the loading overlay. But first, I got an error because there's a comma missing in IntercomWebView.js at IntercomWebView.propTypes.

Missing comma at id.
```
IntercomWebView.propTypes = {
    appId: PropTypes.string,
    name: PropTypes.string,
    email: PropTypes.string,
    id: PropTypes.string || null
    hideLauncher: PropTypes.bool,
    showLoadingOverlay: PropTypes.bool,
    defaultHeight: PropTypes.number,
    userHash: PropTypes.string || null
};

```
https://github.com/donovantc/react-native-intercom-webview/blob/master/IntercomWebView.js

Using the onShouldStartLoadingWithRequest prop for Webviews, I get back this object:
```
Object {
  "canGoBack": false,
  "canGoForward": false,
  "loading": false,
  "lockIdentifier": 3830681759,
  "navigationType": "other",
  "target": 312,
  "title": "",
  "url": "http://192.168.1.87:19001/assets/node_modules/react-native-intercom-webview/IntercomWebView.html?platform=ios&hash=c6790357f0f1b3a4b010949cfa0fb71e",
}
```
It is peculiar to me that in the url, between my local address and node_modules is **/assets/**. For me and I'm sure others, our /node_modules folder is at our root / top level directory. I don't see where I can make an adjust in the code to look instead look at http://192.168.1.87:19001/node_modules/react-native-intercom-webview/.... Or maybe I'm thinking about this wrong?

**Comment by phiyan** [comment] 2018-02-21 06:30
Unfortunately, I'm getting the same error as above:
```
Setting onMessage on a WebView overrides existing values of window.postMessage, but a previous value was defined.
```

Using RN 0.53, iOS, v1.2.4

**Comment by donovantc** [comment] 2018-02-22 08:25
@phiyan I also just noticed that and seems to be an issue with one of the latest versions of RN.

I removed ònMessage` for now and fixed some other small bugs, so please try with the latest version v1.2.5.

**Comment by donovantc** [comment] 2018-04-23 21:15
Closing this due to lack of activity. If you feel the issue is still relevant please let me know. Thanks

**Closed by donovantc** 2018-04-23 21:15 UTC

**Comment by Vincenttbk** [comment] 2018-07-25 04:12
This is still happening in 0.55.4, but it only happens in iOS.
This happens as long as I added a function in onMessage prop when calling the webview
